format = """
[ ](#9A348E)\
$os\
$battery\
$username\
$hostname\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$nodejs\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$python\
$julia\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$cmd_duration\
[](fg:#06969A bg:#33658A)\
[ ](fg:#33658A)
$character
"""



[character]
success_symbol = "[  󱞪❯](fg:#86BBD8)"
error_symbol = "[  󱞪❯](red)"

[battery]
format = "[$symbol](bg:#9A348E)"

[[battery.display]]
threshold = 10
style = 'fg:red bg:#33658A'
discharging_symbol = "󰁺 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 20
style = 'fg:orange bg:#33658A'
discharging_symbol = "󰁻 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 30
style = 'fg:yellow bg:#33658A'
discharging_symbol = "󰁼 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 40
discharging_symbol = "󰁽 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 50
discharging_symbol = "󰁾 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 60
discharging_symbol = "󰁿 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 70
discharging_symbol = "󰂀 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 80
discharging_symbol = "󰂁 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 90
discharging_symbol = "󰂂 "
charging_symbol = "󱐋 "

[[battery.display]]
threshold = 100
discharging_symbol = "󰁹 "
charging_symbol = "󱐋 "

[hostname]
ssh_only = true
ssh_symbol = "󰢹"
format = '[$ssh_symbol on $hostname ]($style)'
# trim_at = '.companyname.com'
style = "bg:#9A348E"
disabled = false

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[os.symbols]
Windows = "\ue8e5 "
Macos = "\ue711 "
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[cmd_duration]
format = "[ \uf520](bg:#06969A)[$duration ](bg:#06969A)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "\ueeff "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'

















